/etc/bareos/bareos-fd.d/client/myself.conf        /usr/lib/bareos/defaultconfigs/bareos-fd.d/client/
/etc/bareos/bareos-fd.d/director/bareos-dir.conf  /usr/lib/bareos/defaultconfigs/bareos-fd.d/director/
/etc/bareos/bareos-fd.d/director/bareos-mon.conf  /usr/lib/bareos/defaultconfigs/bareos-fd.d/director/
/etc/bareos/bareos-fd.d/messages/Standard.conf    /usr/lib/bareos/defaultconfigs/bareos-fd.d/messages/
/etc/bareos/tray-monitor.d/client/FileDaemon-local*.conf /usr/lib/bareos/defaultconfigs/tray-monitor.d/client/
/usr/sbin/bareos-fd
/usr/lib/bareos/plugins/bpipe-fd.so
/usr/share/man/man8/bareos-fd.8.gz
