/usr/lib/bareos/plugins/autoxflate-sd.so
/usr/lib/bareos/scripts/disk-changer
/etc/bareos/bareos-sd.d/device/FileStorage.conf   /usr/lib/bareos/defaultconfigs/bareos-sd.d/device/
/etc/bareos/bareos-sd.d/director/bareos-dir.conf  /usr/lib/bareos/defaultconfigs/bareos-sd.d/director/
/etc/bareos/bareos-sd.d/director/bareos-mon.conf  /usr/lib/bareos/defaultconfigs/bareos-sd.d/director/
/etc/bareos/bareos-sd.d/messages/Standard.conf    /usr/lib/bareos/defaultconfigs/bareos-sd.d/messages/
/etc/bareos/bareos-sd.d/storage/bareos-sd.conf    /usr/lib/bareos/defaultconfigs/bareos-sd.d/storage/
/etc/bareos/tray-monitor.d/storage/StorageDaemon-local*.conf /usr/lib/bareos/defaultconfigs/tray-monitor.d/storage/
/usr/sbin/bareos-sd
/usr/share/man/man8/bareos-sd.8.gz
