#! /usr/bin/dh-exec
/etc/bareos/mtx-changer.conf
/etc/bareos/bareos-dir.d/storage/Tape.conf.example
/etc/bareos/bareos-sd.d/autochanger/autochanger-0.conf.example
/etc/bareos/bareos-sd.d/device/tapedrive-0.conf.example
/usr/lib/bareos/backends/libbareossd-gentape*.so
/usr/lib/bareos/backends/libbareossd-tape*.so
[linux-any] /usr/lib/bareos/plugins/scsicrypto-sd.so
[linux-any] /usr/lib/bareos/plugins/scsitapealert-sd.so
/usr/lib/bareos/scripts/mtx-changer
/usr/share/man/man8/bscrypto.8.gz
/usr/share/man/man8/btape.8.gz
/usr/sbin/bscrypto
/usr/sbin/btape
